# This file is used to configure a system launched by launch/main.launch
# Modify the field given below as applicable
# Note that all fields may not be used in every configurations

# SAMPLER OPTIONS
# specify sampler from ["UniformRectSampler" "UniformCircularSampler"]
sampler_name: "UniformRectSampler"
# probability for sampling goal
goal_sample_p: 0.2
# limits for x and y (valid only for UniformRectSampler)
min_x:  0
max_x:  5
min_y:  0
max_y:  5
# radius and cetre of sampling area (valid only for UniformCircularSampler)
radius: 5
centre: [0, 0]

# PLANNER OPTIONS
# specify planner from ["RRT" "PRM" "PRMStar" "PotentialField" "RRG" "InformedRRTstar"]
planner_name: "PRM"
# maximum radius to look for neighbours
r: 5
# total no. of nodes to be sampled in sample_area
n: 100
# maximum number of iterations per path computation
max_iter: 500

# ENVRIONMENT OPTIONS
# specify environment from ["PolygonEnv" "ScanEnv"]
env_name: "PolygonEnv"
# distance to buffer all obstacles for collision checking
buffer_dist: 0.1
# Initial data
obstacle_data: [[[8, 5], [7, 8], [2, 9], [3, 5]], [[3, 3], [3, 5], [5, 5], [5, 3]]]

# CONTROLLER OPTIONS
# Specify controller from ["DiffPID", "OmniWheelPID"]
controller_name: "OmniWheelPID"
# limits for x and y components of velocity (valid only for OmniWheelPID)
maxX: 1
maxY: 1
# Gains for P, I and D of x and y velocity (valid only for OmniWheelPID)
xgains: [1, 0, 0]
ygains: [1, 0, 0]
# limits for forward and angular velocity (valid only for DiffPID)
maxVel: 1
maxAng: 1
# Gains for P, I and D of forward and angular velocity (valid only for DiffPID)
vel_gains: [1, 0, 0]
angle_gains : [1, 0, 0]

# COMMANDER OPTIONS
# specify start point
start: [0, 0, 0]
# specify goal point
goal: [10, 10, 0]
# desired period between sucessive replan attempts
replan_interval: 10
# type of ROS message used by obstacle data in the
# standard `package/msg_name` format used by ROS
msg_dtype_name: "sensor_msgs/LaserScan"
