name: Lint Check

on: [pull_request]

jobs:
  isort:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            python-version: [3.6, 2.7]
            os: [ubuntu-latest, ubuntu-18.04, windows-latest, macOS-latest]

    steps:
      - uses: olance/isort-action@v1.1.0
