name: Lint Check

on: [push, pull_request]

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup python
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      # Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Lint with black
        run: |
          black --check .

      - name: Lint with isort
        run: |
          isort --profile black -c .
